-- neovim plugins for user interface
require("plugins.barbar")
-- require("plugins.treesitter")
require("plugins.nvimtree")
require("plugins.comment")
-- require("plugins.gitlinker")
-- require("plugins.indentline")
require("plugins.colorizer")
require("plugins.pairs")
require("plugins.surround")
